app/tinyurl/forms.py
import wtforms

from flask import g, current_app
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

from app.tinyurl import common
from core.parsers import BASE62, in_alphabet, is_url


class MakeForm(FlaskForm):
    url = StringField('Long URL', validators=[DataRequired()])
    submit = SubmitField('Make!')

    def validate_url(self, field):
        long_url = field.data
        if not is_url(long_url):
            raise wtforms.ValidationError('URL is invalid')
        short_id = g.tinyurl.get_short_id(long_url=long_url)
        if short_id is not None:
            short_url = common.get_short_url_from_short_id(short_id=short_id)
            raise wtforms.ValidationError(
                'URL is already a TinyURL ({short_url}).'.format(
                    short_url=short_url))


class SearchForm(FlaskForm):
    long_url = StringField('Long URL')
    short_id = StringField('OR, Short ID')
    submit = SubmitField('Search!')

    def validate_long_url(self, field):
        long_url = field.data
        if long_url is None or len(long_url) == 0:
            current_app.logger.debug('Long url is None or empty')
            return
        current_app.logger.debug(
            'Long url: {long_url}'.format(long_url=long_url))
        if not is_url(long_url):
            raise wtforms.ValidationError('Long URL is invalid')
        short_id = g.tinyurl.get_short_id(long_url=long_url)
        if short_id is None:
            raise wtforms.ValidationError(
                'TinyURL does not yet exist for this Long URL')

    def validate_short_id(self, field):
        short_id = field.data
        if short_id is None or len(short_id) == 0:
            current_app.logger.debug('Short id is None or empty')
            return
        current_app.logger.debug(
            'Short id: {short_id}'.format(short_id=short_id))
        if not in_alphabet(short_id, BASE62):
            raise wtforms.ValidationError('Short ID is invalid')
        long_url = g.tinyurl.get_long_url(short_id)
        if long_url is None:
            raise wtforms.ValidationError(
                'TinyURL does not yet exist for this Short ID')

app/__init__.py
import os

from flask import Flask
from flask_bootstrap import Bootstrap

import core.logger
import core.redis
import core.tinyurl


def create_app(testing=False):
    app = Flask(__name__)
    app.config['TESTING'] = testing
    app.config['SECRET_KEY'] = os.environ['TINYURL_SECRET_KEY']

    core.logger.init_app(app)
    core.redis.init_app(app)
    core.tinyurl.init_app(app)

    Bootstrap(app)

    from app.errors import blueprint as errors_blueprint
    app.register_blueprint(errors_blueprint)

    from app.tinyurl import blueprint as tinyurl_blueprint
    app.register_blueprint(tinyurl_blueprint)

    return app

app/tinyurl/__init__.py
from flask import Blueprint

blueprint = Blueprint('tinyurl', __name__)

from app.tinyurl import views

app/tinyurl/views.py
from flask import (
    g, current_app, jsonify, redirect, render_template, request, url_for)
from werkzeug.exceptions import BadRequest, NotFound

from app.tinyurl import common, blueprint
from app.tinyurl.forms import MakeForm, SearchForm
from core.parsers import qr_encode


@blueprint.route('/', methods=['GET', 'POST'])
def make_form():
    form = MakeForm()
    long_url = request.form.get('url')
    if form.validate_on_submit():
        return common.make_short(long_url, is_html=True)
    return render_template('tinyurl/make.html', form=form)


@blueprint.route('/search', methods=['GET', 'POST'])
def search_form():
    form = SearchForm()
    short_id = request.form.get('short_id') or None
    long_url = request.form.get('long_url') or None
    if form.validate_on_submit():
        get_info_endpoint = url_for(
            'tinyurl.get_info', url=long_url, id=short_id, html=True)
        return redirect(get_info_endpoint, code=303)
    return render_template('tinyurl/search.html', form=form)


@blueprint.route('/api', methods=['GET'])
def get_info():
    is_html = request.args.get('html', False)
    if 'url' in request.args and 'id' not in request.args:
        current_app.logger.debug('Found long url in request args')
        long_url = request.args.get('url')
        return _get_info_from_long_url(long_url=long_url, is_html=is_html)
    elif 'url' not in request.args and 'id' in request.args:
        short_id = request.args.get('id')
        return _get_info_from_short_id(short_id=short_id, is_html=is_html)
    else:
        raise BadRequest(
            'Only one of url or id parameters can be set in the query')


def _get_info_from_long_url(long_url, is_html):
    # Sanitize user input
    current_app.logger.info('Request to GET shorten url {long_url}'.format(
        long_url=(long_url or 'empty')))
    common.validate_long_url(long_url)
    # Determine short id
    short_id = g.tinyurl.get_short_id(long_url)
    if short_id is None:
        raise NotFound('TinyURL does not exist')
    else:
        short_url = common.get_short_url_from_short_id(short_id)
        short_qr = qr_encode(short_url)
        payload = dict(
            long_url=long_url,
            short_id=short_id, short_url=short_url, short_qr=short_qr)
        if is_html:
            return render_template('tinyurl/get.html', **payload)
        else:
            return jsonify(payload), 200


def _get_info_from_short_id(short_id, is_html):
    # Sanitize user input
    current_app.logger.info('Request to GET long url from {short_id}'.format(
        short_id=(short_id or 'empty')))
    common.validate_short_id(short_id)
    # Determine long url
    long_url = g.tinyurl.get_long_url(short_id)
    if long_url is None:
        raise NotFound('TinyURL does not exist')
    else:
        short_url = common.get_short_url_from_short_id(short_id)
        short_qr = qr_encode(short_url)
        payload = dict(
            long_url=long_url,
            short_id=short_id, short_url=short_url, short_qr=short_qr)
        if is_html:
            return render_template('tinyurl/get.html', **payload)
        else:
            return jsonify(payload), 200


@blueprint.route('/api', methods=['POST'])
def make_short():
    # Sanitize user input
    if not request.is_json:
        raise BadRequest('Request body is not json')
    body = request.get_json()
    long_url = body.get('url')
    # ...
    return common.make_short(long_url=long_url)


@blueprint.route('/<string:short_id>', methods=['GET'])
def redirect_to_long(short_id):
    # Sanitize user input
    current_app.logger.info(
        'Request to redirect using short id {short_id}'.format(
            short_id=short_id))
    long_url = g.tinyurl.get_long_url(short_id)
    if long_url is None:
        raise NotFound('TinyURL does not exist')
    else:
        # TODO:
        # - show an advertisement
        # - track usage
        return redirect(long_url, code=302)

app/templates/base.html
{% import "bootstrap/utils.html" as utils %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TinyURL Clone | 7okyo.com</title>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <div class="wrapper">
            <div class="content-section">{% include 'menu.html' with context %}</div>
            <div class="intro-header">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="intro-message">
                                <h1>{% block title %}{% endblock %}</h1>
                                <p><i>Implementation of the classic system design interview question.</i></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-section">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            {{ utils.flashed_messages() }}
                            {% block body %}{% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-inline">
                            <li><a href="{{ url_for('tinyurl.make_form') }}">Home</a></li>
                            <li class="footer-menu-divider">⋅</li>
                            <li><a href="https://github.com/eddiecorrigall/tinyurl">GitHub</a></li>
                            <li class="footer-menu-divider">⋅</li>
                            <li><a href="https://linkedin.com/in/eddiecorrigall">LinkedIn</a></li>
                        </ul>
                        <p class="copyright text-muted small">Copyright &copy; 2019. All Rights Reserved</p>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>

app/templates/menu.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('tinyurl.make_form') }}">TinyURL Clone</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('tinyurl.make_form') }}"><span class="glyphicon glyphicon-pencil"></span> Make</a></li>
            <li><a href="{{ url_for('tinyurl.search_form') }}"><span class="glyphicon glyphicon-search"></span> Search</a></li>
        </ul>
    </div>
</nav>

app/templates/tinyurl/get.html
{% extends "base.html" %}

{% block title %}
Get TinyURL
{% endblock %}

{% block body %}
    <table class="table">
        <tbody>
            <tr>
                <th>Short ID</th>
                <td>
                {% if short_id %}
                    {{ short_id }}
                {% else %}
                    Unknown Short ID
                {% endif %}
                </td>
            </tr>
            <tr>
                <th>Short URL</th>
                <td>
                {% if short_url %}
                    <a href="{{ short_url }}">{{ short_url }}</a>
                {% else %}
                    Unknown Short URL
                {% endif %}
                </td>
            </tr>
            <tr>
                <th>Long URL</th>
                <td>
                {% if long_url %}
                    <a href="{{ long_url }}">{{ long_url }}</a>
                {% else %}
                    Unknown Long URL
                {% endif %}
                </td>
            </tr>
            <tr>
                <th>QR Code</th>
                <td>
                {% if short_qr %}
                    <img src="{{ short_qr }}" alt="Short QR" />
                {% endif %}
            </tr>
        </tbody>
    </table>
{% endblock %}

app/templates/tinyurl/make.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}
Make TinyURL
{% endblock %}

{% block body %}
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/tinyurl/search.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}
Search TinyURL
{% endblock %}

{% block body %}
{{ wtf.quick_form(form) }}
{% endblock %}